CREATE SEQUENCE  "CONTRATO"."SQ_RN_CONTRATO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE  NOPARTITION ;

DROP TABLE "CONTRATO"."RN_CONTRATO";
CREATE TABLE "CONTRATO"."RN_CONTRATO" 
(	"COD_RN_CONTRATO" NUMBER(*,0) NOT NULL, 
"COD_REGULACAO_NORMATIVA" NUMBER(*,0) NOT NULL, 
"COD_CONTRATO" NUMBER(*,0) NOT NULL,
"FL_ADEQUADO_CONTRATO" VARCHAR(1) DEFAULT 'N' NOT NULL,
"DT_ADEQUACAO_CONTRATO" DATE NULL,
"NRO_DIAS_PRAZO_BLOQUEIO" NUMBER(*,0) NULL,
cod_tipo_prazo_bloqueio varchar(5) NULL,
DSC_JUSTIFICATIVA varchar(1000) NULL,
DSC_OBSERVACAO varchar(1000) NULL
) ;

ALTER TABLE "CONTRATO"."RN_CONTRATO" ADD CONSTRAINT "PK_RN_CONTRATO" PRIMARY KEY ("COD_RN_CONTRATO") ENABLE;
ALTER TABLE "CONTRATO"."RN_CONTRATO" ADD CONSTRAINT "FK_CONTRATO_3" FOREIGN KEY ("COD_CONTRATO")
	  REFERENCES "CONTRATO"."CONTRATO" ("COD_CONTRATO") ENABLE;
ALTER TABLE "CONTRATO"."RN_CONTRATO" ADD CONSTRAINT "FK_REGULACAO_NORMATIVA_6" FOREIGN KEY ("COD_REGULACAO_NORMATIVA")
	  REFERENCES "CONTRATO"."REGULACAO_NORMATIVA" ("COD_REGULACAO_NORMATIVA") ENABLE;

grant all on SQ_RN_CONTRATO to USER_CONTRATO;
create synonym USER_CONTRATO.SQ_RN_CONTRATO for SQ_RN_CONTRATO;

grant all on RN_CONTRATO to USER_CONTRATO;
create synonym USER_CONTRATO.RN_CONTRATO for RN_CONTRATO;
