/*
Schemas:
1. EMPRESA
2. CONTRATO
3. FATURAMENTO
4. BENEFICIARIO
5. CONTROLE_ACESSO
6. DOCUMENTO
7. ENDERECO
8. MENSAGEM
9. CARTAO
10. CONCENTRADOR_ANS
11. SINCRONISMO
12. IMPORTACAO_VIDA
*/

-- 1. EMPRESA
-- Owner do schema
CREATE USER EMPRESA IDENTIFIED BY dbaq1w2e3;
GRANT UNLIMITED TABLESPACE, CREATE TABLE, CREATE SESSION, CREATE VIEW, CONNECT, DBA TO EMPRESA;

-- Usuario da aplicacao
CREATE ROLE SERVICO_EMPRESA;
CREATE USER USER_EMPRESA IDENTIFIED BY druidq1w2e3;
GRANT CREATE SESSION, CONNECT TO USER_EMPRESA;
GRANT SERVICO_EMPRESA TO USER_EMPRESA

--

-- 2. CONTRATO
-- Owner do schema
CREATE USER CONTRATO IDENTIFIED BY dbaq1w2e3;
GRANT UNLIMITED TABLESPACE, CREATE TABLE, CREATE SESSION, CREATE VIEW, CONNECT, DBA TO CONTRATO;

-- Usuario da aplicacao
CREATE ROLE SERVICO_CONTRATO;
CREATE USER USER_CONTRATO IDENTIFIED BY druidq1w2e3;
GRANT CREATE SESSION, CONNECT TO USER_CONTRATO;
GRANT SERVICO_CONTRATO TO USER_CONTRATO

--

-- 3. FATURAMENTO
-- Owner do schema
CREATE USER FATURAMENTO IDENTIFIED BY dbaq1w2e3;
GRANT UNLIMITED TABLESPACE, CREATE TABLE, CREATE SESSION, CREATE VIEW, CONNECT, DBA TO FATURAMENTO;

-- Usuario da aplicacao
CREATE ROLE SERVICO_FATURAMENTO;
CREATE USER USER_FATURAMENTO IDENTIFIED BY druidq1w2e3;
GRANT CREATE SESSION, CONNECT TO USER_FATURAMENTO;
GRANT SERVICO_FATURAMENTO TO USER_FATURAMENTO

--

-- 4. BENEFICIARIO
-- Owner do schema
CREATE USER BENEFICIARIO IDENTIFIED BY dbaq1w2e3;
GRANT UNLIMITED TABLESPACE, CREATE TABLE, CREATE SESSION, CREATE VIEW, CONNECT, DBA TO BENEFICIARIO;

-- Usuario da aplicacao
CREATE ROLE SERVICO_BENEFICIARIO;
CREATE USER USER_BENEFICIARIO IDENTIFIED BY druidq1w2e3;
GRANT CREATE SESSION, CONNECT TO USER_BENEFICIARIO;
GRANT SERVICO_BENEFICIARIO TO USER_BENEFICIARIO

--

-- 5. CONTROLE_ACESSO
-- Owner do schema
CREATE USER CONTROLE_ACESSO IDENTIFIED BY dbaq1w2e3;
GRANT UNLIMITED TABLESPACE, CREATE TABLE, CREATE SESSION, CREATE VIEW, CONNECT, DBA TO CONTROLE_ACESSO;

-- Usuario da aplicacao
CREATE ROLE SERVICO_CONTROLE_ACESSO;
CREATE USER USER_CONTROLE_ACESSO IDENTIFIED BY druidq1w2e3;
GRANT CREATE SESSION, CONNECT TO USER_CONTROLE_ACESSO;
GRANT SERVICO_CONTROLE_ACESSO TO USER_CONTROLE_ACESSO

--

-- 6. DOCUMENTO
-- Owner do schema
CREATE USER DOCUMENTO IDENTIFIED BY dbaq1w2e3;
GRANT UNLIMITED TABLESPACE, CREATE TABLE, CREATE SESSION, CREATE VIEW, CONNECT, DBA TO DOCUMENTO;

-- Usuario da aplicacao
CREATE ROLE SERVICO_DOCUMENTO;
CREATE USER USER_DOCUMENTO IDENTIFIED BY druidq1w2e3;
GRANT CREATE SESSION, CONNECT TO USER_DOCUMENTO;
GRANT SERVICO_DOCUMENTO TO USER_DOCUMENTO

--

-- 7. ENDERECO
-- Owner do schema
CREATE USER ENDERECO IDENTIFIED BY dbaq1w2e3;
GRANT UNLIMITED TABLESPACE, CREATE TABLE, CREATE SESSION, CREATE VIEW, CONNECT, DBA TO ENDERECO;

-- Usuario da aplicacao
CREATE ROLE SERVICO_ENDERECO;
CREATE USER USER_ENDERECO IDENTIFIED BY druidq1w2e3;
GRANT CREATE SESSION, CONNECT TO USER_ENDERECO;
GRANT SERVICO_ENDERECO TO USER_ENDERECO

--

-- 8. MENSAGEM
-- Owner do schema
CREATE USER MENSAGEM IDENTIFIED BY dbaq1w2e3;
GRANT UNLIMITED TABLESPACE, CREATE TABLE, CREATE SESSION, CREATE VIEW, CONNECT, DBA TO MENSAGEM;

-- Usuario da aplicacao
CREATE ROLE SERVICO_MENSAGEM;
CREATE USER USER_MENSAGEM IDENTIFIED BY druidq1w2e3;
GRANT CREATE SESSION, CONNECT TO USER_MENSAGEM;
GRANT SERVICO_MENSAGEM TO USER_MENSAGEM

--

-- 9. CARTAO
-- Owner do schema
CREATE USER CARTAO IDENTIFIED BY dbaq1w2e3;
GRANT UNLIMITED TABLESPACE, CREATE TABLE, CREATE SESSION, CREATE VIEW, CONNECT, DBA TO CARTAO;

-- Usuario da aplicacao
CREATE ROLE SERVICO_CARTAO;
CREATE USER USER_CARTAO IDENTIFIED BY druidq1w2e3;
GRANT CREATE SESSION, CONNECT TO USER_CARTAO;
GRANT SERVICO_CARTAO TO USER_CARTAO

--

-- 10. CONCENTRADOR_ANS
-- Owner do schema
CREATE USER CONCENTRADOR_ANS IDENTIFIED BY dbaq1w2e3;
GRANT UNLIMITED TABLESPACE, CREATE TABLE, CREATE SESSION, CREATE VIEW, CONNECT, DBA TO CONCENTRADOR_ANS;

-- Usuario da aplicacao
CREATE ROLE SERVICO_CONCENTRADOR_ANS;
CREATE USER USER_CONCENTRADOR_ANS IDENTIFIED BY druidq1w2e3;
GRANT CREATE SESSION, CONNECT TO USER_CONCENTRADOR_ANS;
GRANT SERVICO_CONCENTRADOR_ANS TO USER_CONCENTRADOR_ANS

--

-- 11. SINCRONISMO
-- Owner do schema
CREATE USER SINCRONISMO IDENTIFIED BY dbaq1w2e3;
GRANT UNLIMITED TABLESPACE, CREATE TABLE, CREATE SESSION, CREATE VIEW, CONNECT, DBA TO SINCRONISMO;

-- Usuario da aplicacao
CREATE ROLE SERVICO_SINCRONISMO;
CREATE USER USER_SINCRONISMO IDENTIFIED BY druidq1w2e3;
GRANT CREATE SESSION, CONNECT TO USER_SINCRONISMO;
GRANT SERVICO_SINCRONISMO TO USER_SINCRONISMO

--

-- 12. IMPORTACAO_VIDA
-- Owner do schema
CREATE USER IMPORTACAO_VIDA IDENTIFIED BY dbaq1w2e3;
GRANT UNLIMITED TABLESPACE, CREATE TABLE, CREATE SESSION, CREATE VIEW, CONNECT, DBA TO IMPORTACAO_VIDA;

-- Usuario da aplicacao
CREATE ROLE SERVICO_IMPORTACAO_VIDA;
CREATE USER USER_IMPORTACAO_VIDA IDENTIFIED BY druidq1w2e3;
GRANT CREATE SESSION, CONNECT TO USER_IMPORTACAO_VIDA;
GRANT SERVICO_IMPORTACAO_VIDA TO USER_IMPORTACAO_VIDA

--
