-- Concede permissoes especificas para roles de outrso microservicos

-- Filtro Empresa
GRANT SELECT ON CONTRATO.VIGENCIA_CONTRATO TO EMPRESA WITH GRANT OPTION;
GRANT SELECT ON CONTRATO.CONTRATO TO EMPRESA WITH GRANT OPTION;
GRANT SELECT ON EMPRESA.FILTRO_CONTRATO_EMPRESA TO SERVICO_EMPRESA;

-- Filtro Beneficiario
GRANT SELECT ON CONTRATO.CONTRATO_PLANO TO BENEFICIARIO WITH GRANT OPTION;
GRANT SELECT ON CONTRATO.CONTRATO TO BENEFICIARIO WITH GRANT OPTION;
GRANT SELECT ON CONTRATO.TIPO_CONTRATO TO BENEFICIARIO WITH GRANT OPTION;
GRANT SELECT ON CONTRATO.PLANO_HIGIA TO BENEFICIARIO WITH GRANT OPTION;
GRANT SELECT ON CONTRATO.MODELO TO BENEFICIARIO WITH GRANT OPTION;
GRANT SELECT ON EMPRESA.EMPRESA TO BENEFICIARIO WITH GRANT OPTION;
GRANT SELECT ON BENEFICIARIO.FILTRO_CONTRATO_BENEFICIARIO TO SERVICO_BENEFICIARIO;

-- View SIB
/*
BENEFICIARIO.pessoa_fisica
BENEFICIARIO.beneficiario
BENEFICIARIO.vinculo
BENEFICIARIO.ativacao
*/
GRANT SELECT ON CONTRATO.contrato_plano TO BENEFICIARIO WITH GRANT OPTION;
GRANT SELECT ON CONTRATO.contrato TO BENEFICIARIO WITH GRANT OPTION;
GRANT SELECT ON CONTRATO.contrato_produto TO BENEFICIARIO WITH GRANT OPTION;
GRANT SELECT ON CONTRATO.produto_ANS_higia TO BENEFICIARIO WITH GRANT OPTION;
GRANT SELECT ON CONTRATO.grau_parentesco TO BENEFICIARIO WITH GRANT OPTION;
GRANT SELECT ON ENDERECO.beneficiario_endereco TO BENEFICIARIO WITH GRANT OPTION;
GRANT SELECT ON ENDERECO.endereco TO BENEFICIARIO WITH GRANT OPTION;
GRANT SELECT ON EMPRESA.empresa TO BENEFICIARIO WITH GRANT OPTION;
GRANT SELECT ON CONTRATO.contrato_exclusao TO BENEFICIARIO WITH GRANT OPTION;