-- BENEFICIARIO INICIO

CREATE TABLE BENEFICIARIO.PRECO_LIMINAR_JUDICIAL
  (
    COD_PRECO_LIMINAR_JUD NUMBER (*,0) NOT NULL ,
    DATA_RELACAO          DATE ,
    COD_LIMINAR_JUDICIAL           NUMBER (*,0)
  )
  LOGGING ;
  

ALTER TABLE BENEFICIARIO.PRECO_LIMINAR_JUDICIAL ADD CONSTRAINT PRECO_LIMINAR_JUDICIAL_PK PRIMARY KEY ( COD_PRECO_LIMINAR_JUD ) ;

CREATE SEQUENCE SQ_PRECO_LIMINAR_JUDICIAL START WITH 0 MINVALUE 0 MAXVALUE 9223372036854775807 NOCYCLE;

ALTER TABLE BENEFICIARIO.PRECO_LIMINAR_JUDICIAL ADD CONSTRAINT LIMINAR_JUDI_BENE_FK FOREIGN KEY ( COD_LIMINAR_JUDICIAL ) REFERENCES BENEFICIARIO.LIMINAR_JUDICIAL ( COD_LIMINAR_JUDICIAL ) NOT DEFERRABLE ;

-- BENEFICIARIO FIM

