---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/druid-rio/saofrancisco-microservices
          searchPaths: config-repository
        native:
          searchLocations: classpath:offline-repository/
server:
  port: 8001

---
spring:
    profiles: local
    name: local-files
    environment: test
    cloud:
        config:
          server:
          native:
            searchLocations: file://${repo.folder}/config-repository


