---
server:
  port: 8001

---
spring:
  profiles: default
  default: default
  cloud:
    config:
      server:
        git:
          uri: https://github.com/druid-rio/saofrancisco-microservices
          searchPaths: config-repository
        native:
          searchLocations: classpath:offline-repository/

---
spring:
  profiles: native

  cloud:
    config:
      server:
        native:
          searchLocations: file:${repo.folder}/config-repository
logging:
  level:
    org.springframework: INFO


