---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/druid-rio/saofrancisco-microservices
          searchPaths: config-repository
        native:
          searchLocations: classpath:offline-repository/
server:
  port: 8001


