---
spring:
  application:
    name: address
  datasource:
    url: jdbc:oracle:thin:@//sf-dsv.chapsiz2x54b.us-west-2.rds.amazonaws.com:1521/ORCL
    username: ENDERECO
    password: druidq1w2e3
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ddl-auto: none
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.hbm2ddl.auto: validate
server:
  port: 8087
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  datacenter: cloud
  instance:
    statusPageUrlPath: /eureka/info
    healthCheckUrlPath: /eureka/health
management:
  contextPath: /eureka


---
spring:
  profiles: dsv
  application:
    name: address
  datasource:
    url: jdbc:oracle:thin:@//sf-dsv.chapsiz2x54b.us-west-2.rds.amazonaws.com:1521/ORCL
    username: ENDERECO
    password: druidq1w2e3
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ddl-auto: none
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.hbm2ddl.auto: validate
server:
  port: 8087
eureka:
  client:
    serviceUrl:
      defaultZone: http://35.166.252.70:8761/eureka/
  datacenter: cloud
  instance:
    statusPageUrlPath: /eureka/info
    healthCheckUrlPath: /eureka/health
management:
  contextPath: /eureka


