---
spring:
  profiles: default
  application:
    name: api-gateway   
server:
  port: 9090
zuul:
  routes:
    customer: /mycustomer/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: dsv
  application:
    name: api-gateway   
server:
  port: 80
zuul:
  prefix: /services
management:
  contextPath: /eureka
eureka:
  instance:
    statusPageUrlPath: /eureka/info
    healthCheckUrlPath: /eureka/health
  datacenter: cloud
  client:
    serviceUrl:
      defaultZone: http://35.166.252.70:8761/eureka/
