---
spring:
  application:
    name: api-gateway   
server:
  port: 9091
zuul:
  host:
    connect-timeout-millis: 90000
    socket-timeout-millis: 90000
  sensitiveHeaders:
  prefix: /services
  routes:
    oauth-server:
      sensitiveHeaders:
      path: /oauth/**
      stripPrefix: false
  add-proxy-headers: true
management:
  contextPath: /eureka
eureka:
  instance:
    statusPageUrlPath: /eureka/info
    healthCheckUrlPath: /eureka/health
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
ribbon:
  ConnectTimeout: 90000
  ReadTimeout: 90000
security:
  basic:
    enabled: false
  oauth2:
    client:
      accessTokenUri: http://oauth-server/oauth/token
      userAuthorizationUri: /services/oauth-server/oauth/token
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 90000  

---
spring:
  profiles: dsv
  application:
    name: api-gateway   
server:
  port: 80
zuul:
  prefix: /services
management:
  contextPath: /eureka
eureka:
  instance:
    statusPageUrlPath: /eureka/info
    healthCheckUrlPath: /eureka/health
  datacenter: cloud
  client:
    serviceUrl:
      defaultZone: http://35.166.252.70:8761/eureka/
ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 30000
security:
  basic:
    enabled: false
  oauth2:
    client:
      accessTokenUri: http://oauth-server/oauth/token
      userAuthorizationUri: /services/oauth-server/oauth/token
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000


---
spring:
  profiles: homologSF
  application:
    name: api-gateway   
server:
  port: 9090
zuul:
  prefix: /services
management:
  contextPath: /eureka
eureka:
  instance:
    statusPageUrlPath: /eureka/info
    healthCheckUrlPath: /eureka/health
  client:
    serviceUrl:
      defaultZone: http://service-discovery-homolog:8761/eureka/
  datacenter: saofrancisco-homolog
ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 30000
security:
  basic:
    enabled: false
  oauth2:
    client:
      accessTokenUri: http://oauth-server/oauth/token
      userAuthorizationUri: /services/oauth-server/oauth/token
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000


---
spring:
  profiles: DSV_BD_SF
  application:
    name: api-gateway   
server:
  port: 9090
zuul:
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000
  sensitiveHeaders:
  prefix: /services
  routes:
    oauth-server:
      sensitiveHeaders:
      path: /oauth/**
      stripPrefix: false
  add-proxy-headers: true
management:
  contextPath: /eureka
eureka:
  instance:
    statusPageUrlPath: /eureka/info
    healthCheckUrlPath: /eureka/health
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 30000
security:
  basic:
    enabled: false
  oauth2:
    client:
      accessTokenUri: http://oauth-server/oauth/token
      userAuthorizationUri: /services/oauth-server/oauth/token
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000  
---
spring:
  profiles: teste_sf
  application:
    name: api-gateway   
server:
  port: 9090
zuul:
  prefix: /services
management:
  contextPath: /eureka
eureka:
  instance:
    statusPageUrlPath: /eureka/info
    healthCheckUrlPath: /eureka/health
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  datacenter: saofrancisco-homolog
ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 30000
security:
  basic:
    enabled: false
  oauth2:
    client:
      accessTokenUri: http://oauth-server/oauth/token
      userAuthorizationUri: /services/oauth-server/oauth/token
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000


