---
spring:
  profiles: dsv
  application:
    name: api-gateway   
server:
  port: 80
zuul:
  prefix: /services
management:
  contextPath: /eureka
eureka:
  datacenter: DSV
  environment: DSV
  instance:
    hostname: localhost
    preferIpAddress: false
  client:
    serviceUrl:
      defaultZone: http://35.166.252.70:8761/eureka/
