---
spring:
  application:
    name: api-gateway   
server:
  port: 9090
zuul:
  sensitiveHeaders:
  prefix: /services
  routes:
    oauth-server:
      sensitiveHeaders:
      path: /oauth/**
      stripPrefix: false
  add-proxy-headers: true
management:
  contextPath: /eureka
eureka:
  instance:
    statusPageUrlPath: /eureka/info
    healthCheckUrlPath: /eureka/health
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    ROOT: DEBUG
ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 30000
security:
  basic:
    enabled: false
  oauth2:
    client:
      accessTokenUri: http://oauth-server/oauth/token
      userAuthorizationUri: /services/oauth-server/oauth/token
      clientId: acme
      clientSecret: acmesecret
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----
      id: openid
      serviceId: ${PREFIX:}resource

---
spring:
  profiles: dsv
  application:
    name: api-gateway   
server:
  port: 80
zuul:
  prefix: /services
management:
  contextPath: /eureka
eureka:
  instance:
    statusPageUrlPath: /eureka/info
    healthCheckUrlPath: /eureka/health
  datacenter: cloud
  client:
    serviceUrl:
      defaultZone: http://35.166.252.70:8761/eureka/


