---
spring:
  profiles: dsv
  application:
    name: api-gateway   
server:
  port: 8080
zuul:
  prefix: /services
management:
  contextPath: /eureka
eureka:
  datacenter: DSV
  environment: DSV
  instance:
    hostname: localhost
    preferIpAddress: false
  client:
    serviceUrl:
      defaultZone: http://ec2-54-218-14-0.us-west-2.compute.amazonaws.com:8081/eureka/
