---
spring:
  application:
    name: card
  output:
    ansi:
      enabled: NEVER
  datasource:
    url: jdbc:oracle:thin:@//sf-dsv.chapsiz2x54b.us-west-2.rds.amazonaws.com:1521/ORCL
    username: CARTAO
    password: druidq1w2e3
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 1
      maximum-pool-size: 5
  rabbitmq:
    host: 129.150.65.116		
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cloud:
    stream:
      bindings:
        worksAudit:
          binder: rabbit
          destination: card.audit
          contentType: application/json
        worksBeneficiaryEvents:
          binder: rabbit
          destination: beneficiary.events
          contentType: application/json
          group: cardService2
server:
  port: 8099
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  datacenter: cloud
  instance:
    statusPageUrlPath: /eureka/info
    healthCheckUrlPath: /eureka/health
management:
  contextPath: /eureka
hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
feign:
  hystrix:
    enabled: true
logging:
  level:
    org.springframework.cloud.stream: DEBUG


---
spring:
  profiles: dsv
  application:
    name: card
  output:
    ansi:
      enabled: NEVER
  datasource:
    url: jdbc:oracle:thin:@//sf-dsv.chapsiz2x54b.us-west-2.rds.amazonaws.com:1521/ORCL
    username: CARTAO
    password: druidq1w2e3
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 1
      maximum-pool-size: 5
  rabbitmq:
    host: 129.150.65.116
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cloud:
    stream:
      bindings:
        worksAudit:
          binder: rabbit
          destination: card.audit
          contentType: application/json
        worksBeneficiaryEvents:
          binder: rabbit
          destination: beneficiary.events
          contentType: application/json
          group: cardService2
server:
  port: 8099
eureka:
  client:
    serviceUrl:
      defaultZone: http://35.166.252.70:8761/eureka/
  datacenter: cloud
  instance:
    statusPageUrlPath: /eureka/info
    healthCheckUrlPath: /eureka/health
management:
  contextPath: /eureka
hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
feign:
  hystrix:
    enabled: true

---
spring:
  profiles: homolog
  application:
    name: card
  datasource:
    url: jdbc:oracle:thin:@//sf-dsv.chapsiz2x54b.us-west-2.rds.amazonaws.com:1521/ORCL
    username: CARTAO
    password: druidq1w2e3
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 1
      maximum-pool-size: 5
  rabbitmq:
    host: 129.150.65.116
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cloud:
    stream:
      bindings:
        worksAudit:
          binder: rabbit
          destination: card.audit
          contentType: application/json
        worksBeneficiaryEvents:
          binder: rabbit
          destination: beneficiary.events
          contentType: application/json
          group: cardService2
server:
  port: 8099
eureka:
  client:
    serviceUrl:
      defaultZone: http://35.162.116.175:8761/eureka/
  datacenter: cloud
  instance:
    statusPageUrlPath: /eureka/info
    healthCheckUrlPath: /eureka/health
management:
  contextPath: /eureka
hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
feign:
  hystrix:
    enabled: true

