---
spring:
  application:
    name: contract
  datasource:
    url: jdbc:oracle:thin:@//sf-dsv.chapsiz2x54b.us-west-2.rds.amazonaws.com:1521/ORCL
    username: CONTRATO
    password: druidq1w2e3
    driver-class-name: oracle.jdbc.OracleDriver
    tomcat:
      maxActive: 5	
      maxIdle: 2
      minIdle: 1
      initialSize: 1
  rabbitmq:
    host: localhost		
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cloud:
    stream:
      bindings:
        worksAudit:
          binder: rabbit
          destination: contract.audit
          contentType: application/json
server:
  port: 8088
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  datacenter: cloud
  instance:
    statusPageUrlPath: /eureka/info
    healthCheckUrlPath: /eureka/health
management:
  contextPath: /eureka
logging:
  level:
    org.springframework.cloud.stream: DEBUG


---
spring:
  profiles: dsv
  application:
    name: contract
  datasource:
    url: jdbc:oracle:thin:@//sf-dsv.chapsiz2x54b.us-west-2.rds.amazonaws.com:1521/ORCL
    username: CONTRATO
    password: druidq1w2e3
    driver-class-name: oracle.jdbc.OracleDriver
    tomcat:
      maxActive: 5	
      maxIdle: 2
      minIdle: 1
      initialSize: 1
  rabbitmq:
    host: 129.150.65.116
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cloud:
    stream:
      bindings:
        worksAudit:
          binder: rabbit
          destination: contract.audit
          contentType: application/json
server:
  port: 8088
eureka:
  client:
    serviceUrl:
      defaultZone: http://35.166.252.70:8761/eureka/
  datacenter: cloud
  instance:
    statusPageUrlPath: /eureka/info
    healthCheckUrlPath: /eureka/health
management:
  contextPath: /eureka


