---
spring:
  application:
    name: daemon
  output:
    ansi:
      enabled: NEVER
  datasource:
    url: jdbc:oracle:thin:@//sf-dsv.chapsiz2x54b.us-west-2.rds.amazonaws.com:1521/ORCL
    username: CONCENTRADOR_ANS
    password: druidq1w2e3
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 1
      maximum-pool-size: 5
  rabbitmq:
    host: 129.150.65.116
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: false
      javax:
        persistence:
          validation:
            mode: none
  cloud:
    stream:
      bindings:
        worksBeneficiaryEvents:
          binder: rabbit
          destination: beneficiary.events
          contentType: application/json
          group: sib.daemon         
server:
  port: 8098
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  datacenter: cloud
  instance:
    statusPageUrlPath: /eureka/info
    healthCheckUrlPath: /eureka/health
management:
  contextPath: /eureka


---
spring:
  profiles: dsv
  application:
    name: daemon
  datasource:
    url: jdbc:oracle:thin:@//sf-dsv.chapsiz2x54b.us-west-2.rds.amazonaws.com:1521/ORCL
    username: CONCENTRADOR_ANS
    password: druidq1w2e3
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: false
  rabbitmq:
    host: 129.150.65.116
  cloud:
    stream:
      bindings:
        worksBeneficiaryEvents:
          binder: rabbit
          destination: beneficiary.events
          contentType: application/json
          group: sib.daemon
server:
  port: 8098
eureka:
  client:
    serviceUrl:
      defaultZone: http://35.166.252.70:8761/eureka/
  datacenter: cloud
  instance:
    statusPageUrlPath: /eureka/info
    healthCheckUrlPath: /eureka/health
management:
  contextPath: /eureka


---
spring:
  profiles: homologSF
  application:
    name: daemon
  datasource:
    url: jdbc:oracle:thin:@//10.10.0.70:1521/higiadsv
    username: CONCENTRADOR_ANS
    password: druidq1w2e3
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: false
  rabbitmq:
    host: vm-linux-higia-001
  cloud:
    stream:
      bindings:
        worksBeneficiaryEvents:
          binder: rabbit
          destination: beneficiary.events
          contentType: application/json
          group: sib.daemon      
server:
  port: 8098
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.112.13:8761/eureka/
  datacenter: cloud
  instance:
    statusPageUrlPath: /eureka/info
    healthCheckUrlPath: /eureka/health
management:
  contextPath: /eureka
