---
spring:
  application:
    name: document
  datasource:
    url: jdbc:oracle:thin:@//sf-dsv.chapsiz2x54b.us-west-2.rds.amazonaws.com:1521/ORCL
    username: USER_DOCUMENTO
    password: druidq1w2e3
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 1
      maximum-pool-size: 5
  rabbitmq:
    host: 129.150.65.116		
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate:
        show_sql: true
<<<<<<< HEAD
        format_sql: false
=======
        format_sql: true
  http:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 20MB
>>>>>>> 3a752b7aa1d6f87d57ebee78fafd6a58add9fee6
  cloud:
    stream:
      bindings:
        worksAudit:
          binder: rabbit
          destination: document.audit
          contentType: application/json
        worksDocumentAudit:
          binder: rabbit
          destination: document.audit
          contentType: application/json
          group: documentService
server:
  port: 8086
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  datacenter: cloud
  instance:
    statusPageUrlPath: /eureka/info
    healthCheckUrlPath: /eureka/health
management:
  contextPath: /eureka


---
spring:
  profiles: dsv
  application:
    name: document
  datasource:
    url: jdbc:oracle:thin:@//sf-dsv.chapsiz2x54b.us-west-2.rds.amazonaws.com:1521/ORCL
    username: USER_DOCUMENTO
    password: druidq1w2e3
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 1
      maximum-pool-size: 5
  rabbitmq:
    host: 129.150.65.116	
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: false
      javax:
        persistence:
          validation:
            mode: none
  http:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 20MB
  cloud:
    stream:
      bindings:
        worksAudit:
          binder: rabbit
          destination: document.audit
          contentType: application/json
        worksDocumentAudit:
          binder: rabbit
          destination: document.audit
          contentType: application/json
          group: documentService
server:
  port: 8086
eureka:
  client:
    serviceUrl:
      defaultZone: http://35.166.252.70:8761/eureka/
  datacenter: cloud
  instance:
    statusPageUrlPath: /eureka/info
    healthCheckUrlPath: /eureka/health
management:
  contextPath: /eureka

---
spring:
  profiles: homologSF
  application:
    name: document
  datasource:
    url: jdbc:oracle:thin:@//oracle-database-homolog:1521/higiadsv
    username: USER_DOCUMENTO
    password: druidq1w2e3
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 1
      maximum-pool-size: 5
  rabbitmq:
    host: rabbit-homolog	
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: false
      javax:
        persistence:
          validation:
            mode: none
  cloud:
    stream:
      bindings:
        worksAudit:
          binder: rabbit
          destination: document.audit
          contentType: application/json
        worksDocumentAudit:
          binder: rabbit
          destination: document.audit
          contentType: application/json
          group: documentService
server:
  port: 8086
eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery-homolog:8761/eureka/
  datacenter: saofrancisco-homolog
  instance:
    statusPageUrlPath: /eureka/info
    healthCheckUrlPath: /eureka/health
management:
  contextPath: /eureka



