---
spring:
  profiles: default
  application:
    name: service-discovery   
server:
  port: 8761
management:
  contextPath: /eureka

eureka:
  datacenter: cloud
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
eureka:
  instance:
    statusPageUrlPath: /eureka/info
    healthCheckUrlPath: /eureka/health
  datacenter: cloud
  client:
    serviceUrl:
      defaultZone: http://35.166.252.70:8761/eureka/



---
spring:
  profiles: dsv
  application:
    name: service-discovery   
server:
  port: 8761
management:
  contextPath: /eureka
eureka:
  instance:
    statusPageUrlPath: /eureka/info
    healthCheckUrlPath: /eureka/health
  datacenter: cloud
  client:
    serviceUrl:
      defaultZone: http://35.166.252.70:8761/eureka/

