---
spring:
  profiles: default
  application:
    name: service-discovery   
server:
  port: 8761
eureka:
  datacenter: cloud
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://35.166.252.70:8761/eureka/



---
spring:
  profiles: dsv
  application:
    name: service-discovery   
server:
  port: 8761
eureka:
  datacenter: cloud
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://35.166.252.70:8761/eureka/

