---
spring:
  application:
    name: service-discovery   
server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

---
spring:
  profiles: dsv
  application:
    name: service-discovery   
server:
  port: 8761
eureka:
  datacenter: cloud
  client:
    registerWithEureka: false
    fetchRegistry: false
    region: us-west-2
    serviceUrl:
      defaultZone: http://ec2-35-166-252-70.us-west-2.compute.amazonaws.com:8761/eureka/


---
spring:
  profiles: homologSF
  application:
    name: service-discovery   
server:
  port: 8761
eureka:
  datacenter: saofrancisco-homolog
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://service-discovery-homolog:8761/eureka/ 

---
spring:
  profiles: DSV_BD_SF
  application:
    name: service-discovery   
server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
