---
spring:
  profiles: dsv
  application:
    name: service-discovery   
server:
  port: 8761
management:
  contextPath: /eureka

eureka:
  datacenter: DSV
  environment: DSV
  awsBindingStrategy: ENI
  instance:
    preferIpAddress: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0

