---
spring:
  application:
    name: sync
    output:
      ansi:
        enabled: NEVER
  rabbitmq:
    host: 129.150.65.116

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: false
      javax:
        persistence:
          validation:
            mode: none

  cloud:
    stream:
      bindings:
        worksSyncIn:
          binder: rabbit
          destination: sincronismo.in
          contentType: application/json
          group: syncService
        worksSyncOut:
          binder: rabbit
          destination: sincronismo.out
          contentType: application/json
          group: syncService
        worksCompanyAudit:
          binder: rabbit
          destination: company.audit
          contentType: application/json
          group: synch

server:
  port: 8092

sf:
  client:
    clientId: pei_angular
    clientSecret: druidq1w2e3
    accessTokenUri: http://35.166.252.70:9091/oauth/token
    scope: write
    username: thiago.antas@druid.com.br
    password: 1234

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  datacenter: cloud
  instance:
    statusPageUrlPath: /eureka/info
    healthCheckUrlPath: /eureka/health
management:
  contextPath: /eureka
hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 90000
feign:
  hystrix:
    enabled: true

logging:
  level:
    org.springframework.cloud.stream: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type: TRACE
    br.com.druid.healthinsurance: DEBUG
    #org.springframework.http: TRACE
    #org.apache.http: TRACE

---
spring:
  profiles: homologSF
  application:
    name: sync

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: false
      javax:
        persistence:
          validation:
            mode: none

  cloud:
    stream:
      bindings:
        worksSyncIn:
          binder: sync_rabbit
          destination: sincronismo.in
          contentType: application/json
          group: syncService
        worksSyncOut:
          binder: sync_rabbit
          destination: sincronismo.out
          contentType: application/json
          group: syncService
        worksCompanyAudit:
          binder: services_rabbit
          destination: company.audit
          contentType: application/json
          group: synch
      binders:
        sync_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.112.15
        services_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: rabbit-homolog
                username: sincronismo
                password: sincronismo
      default-binder: services_rabbit

server:
  port: 8092

sf:
  client:
    clientId: pei_angular
    clientSecret: druidq1w2e3
    accessTokenUri: http://35.166.252.70:9091/oauth/token
    scope: write
    username: thiago.antas@druid.com.br
    password: 1234

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery-homolog:8761/eureka/
  datacenter: saofrancisco-homolog
  instance:
    statusPageUrlPath: /eureka/info
    healthCheckUrlPath: /eureka/health
management:
  contextPath: /eureka
hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
feign:
  hystrix:
    enabled: true
