---
spring:
  rabbitmq:
      host: 129.150.65.116

  cloud:
    stream:
      bindings:
        worksSyncIn:
          binder: rabbit
          destination: sincronismo
          contentType: application/json
          group: syncService.in
        worksSyncOut:
          binder: rabbit
          destination: sincronismo
          contentType: application/json
          group: syncService.out
        worksCompanyAudit:
          binder: rabbit
          destination: company.audit
          contentType: application/json
          group: synch
sf:
  client:
    clientId: pei_angular
    clientSecret: druidq1w2e3
    accessTokenUri: http://35.166.252.70:9091/oauth/token
    scope: write
    username: thiago.antas@druid.com.br
    password: 1234

eureka:
  client:
    serviceUrl:
      defaultZone: http://35.166.252.70:8761/eureka/
  datacenter: cloud
  instance:
    statusPageUrlPath: /eureka/info
    healthCheckUrlPath: /eureka/health
management:
  contextPath: /eureka
hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
feign:
  hystrix:
    enabled: true
logging:
  level:
    org.springframework.cloud.stream: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type: TRACE
    br.com.druid.healthinsurance: DEBUG
    #org.springframework.http: TRACE
    #org.apache.http: TRACE
